"""APEX Master Registries — Sprint 19, Appendices A-K."""

from __future__ import annotations

from apex_registries.framework import (
    PRACTICE_CODES,
    REGISTRY_DIRS,
    REGISTRY_MODELS,
    ArchetypeEntry,
    CompetitiveEntry,
    ExerciseEntry,
    KpiEntry,
    McpToolEntry,
    PartnerEntry,
    PersonaEntry,
    ProductEntry,
    RegistryEntry,
    RegistryIssue,
    RegistryReport,
    SchemaEntry,
    discovery_root,
    list_discovery,
    list_playbooks,
    list_preclearance,
    load_entry,
    load_playbook,
    package_root,
    playbooks_root,
    preclearance_root,
    registry_root,
    scan_all_registries,
    scan_registry,
    total_entries,
    validate_registries,
)

__all__ = [
    "PRACTICE_CODES",
    "REGISTRY_DIRS",
    "REGISTRY_MODELS",
    "ArchetypeEntry",
    "CompetitiveEntry",
    "ExerciseEntry",
    "KpiEntry",
    "McpToolEntry",
    "PartnerEntry",
    "PersonaEntry",
    "ProductEntry",
    "RegistryEntry",
    "RegistryIssue",
    "RegistryReport",
    "SchemaEntry",
    "discovery_root",
    "list_discovery",
    "list_playbooks",
    "list_preclearance",
    "load_entry",
    "load_playbook",
    "package_root",
    "playbooks_root",
    "preclearance_root",
    "registry_root",
    "scan_all_registries",
    "scan_registry",
    "total_entries",
    "validate_registries",
]

__version__ = "0.1.0"
