"""APEX RC schema field definitions — single source of truth for the
tree-view popup on the by-service HTML.

Every entity that appears in any scenario chain has a hand-authored field
set here. Where the apex-rc YAML manifest already covered an entity, the
fields are aligned. Where it didn't, the fields follow the same naming
convention (snake_case, _ts for timestamps, _id for surrogate keys,
_natural for natural keys, _token for tokenized PII/PCI).

Every entity also gets a shared audit/lineage tail
(source_system, source_record_id, ingest_ts, record_hash, ledger_row_id).
"""
from __future__ import annotations

# Common audit tail attached to every entity at render time
AUDIT_TAIL = [
    {"name": "source_system",     "type": "string",    "nullable": False, "desc": "Originating system code (POS, OMS, WMS, ERP, CDP, MAP)."},
    {"name": "source_record_id",  "type": "string",    "nullable": False, "desc": "Stable identifier in the source system for replay and reconciliation."},
    {"name": "ingest_ts",         "type": "timestamp", "nullable": False, "desc": "Wall-clock time the row landed in Bronze."},
    {"name": "record_hash",       "type": "string",    "nullable": False, "desc": "SHA-256 of the canonical payload — drives idempotency and change detection."},
    {"name": "ledger_row_id",     "type": "string",    "nullable": True,  "desc": "Forward link to the APEX LEDGER WORM row that emitted or consumed this record."},
]

# Helper to keep the dict readable
def _f(name, type_, nullable=False, key=False, classification=None, enum=None, desc=""):
    d = {"name": name, "type": type_, "nullable": nullable, "desc": desc}
    if key: d["key"] = True
    if classification: d["classification"] = classification
    if enum: d["enum"] = enum
    return d


SCHEMA_FIELDS: dict[str, dict] = {

    # ============================================================
    # MERML — Merchandising (12 entities)
    # ============================================================
    "MERML.Item": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Silver",
        "description": "Canonical merchandising item — the SKU as the merchant categorizes, prices, and ranges it. The anchor identifier across pricing, assortment, and planogram entities.",
        "primary_key": ["item_id"],
        "fields": [
            _f("item_id",         "string",  False, key=True, desc="Internal canonical item identifier."),
            _f("gtin",            "string",  True,  desc="GS1 GTIN-14 — the global trade item number."),
            _f("upc",             "string",  True,  desc="UPC-A 12-digit, where assigned."),
            _f("vendor_id",       "string",  False, desc="FK → MERML.Vendor."),
            _f("category_path",   "string",  False, desc="Slash-delimited category path, e.g. 'Apparel/Tops/Tees'."),
            _f("item_status",     "string",  False, enum=["ACTIVE","NEW","DISCONTINUED","RECALLED"], desc="Lifecycle state."),
            _f("unit_of_measure", "string",  False, desc="EA, CASE, LB, KG, PK."),
            _f("pack_size",       "integer", True,  desc="Inner-pack count when sold as multi-unit."),
            _f("brand",           "string",  True,  desc="Brand label as it appears on shelf."),
            _f("private_label",   "boolean", False, desc="True for retailer private-label items."),
            _f("launch_date",     "date",    True,  desc="First day item is sellable."),
            _f("eol_date",        "date",    True,  desc="Planned end-of-life / discontinuation date."),
        ],
    },
    "MERML.Concept": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Silver",
        "description": "A merchandising concept — a marketing-driven grouping of items (e.g., 'back-to-school', 'sustainable basics') that crosses categories. Used for storytelling, range, and seasonal-buy planning.",
        "primary_key": ["concept_id"],
        "fields": [
            _f("concept_id",     "string",  False, key=True, desc="Concept identifier."),
            _f("concept_name",   "string",  False, desc="Customer-facing or merchant-facing label."),
            _f("season_code",    "string",  True,  desc="Tied season (e.g., 'FW26', 'SS27')."),
            _f("category_scope", "array<string>", True, desc="Categories the concept spans."),
            _f("active_from",    "date",    False, desc="First active date."),
            _f("active_to",      "date",    True,  desc="Sunset date, if any."),
            _f("owner",          "string",  False, desc="Concept owner (merchant or marketing lead)."),
            _f("status",         "string",  False, enum=["DRAFT","APPROVED","LIVE","SUNSET"], desc="Lifecycle state."),
        ],
    },
    "MERML.Promotion": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Silver",
        "description": "Promotion definition — a price or value mechanic offered for a window. Composes with MERML.Markdown for clearance and CXML.Offer for personalized variants.",
        "primary_key": ["promotion_id"],
        "fields": [
            _f("promotion_id",      "string",  False, key=True, desc="Unique promotion identifier."),
            _f("promotion_type",    "string",  False, enum=["PERCENT_OFF","DOLLAR_OFF","BOGO","BUNDLE","REWARD"], desc="Mechanic family."),
            _f("discount_value",    "decimal", False, desc="Mechanic value (percent or dollar)."),
            _f("currency_code",     "string",  True,  desc="ISO-4217 if dollar-based."),
            _f("eligible_items",    "array<string>", True, desc="FK list → MERML.Item.item_id."),
            _f("eligible_audiences","array<string>", True, desc="FK list → CXML.Audience.audience_id."),
            _f("starts_at",         "timestamp", False, desc="Promo activation."),
            _f("ends_at",           "timestamp", False, desc="Promo expiration."),
            _f("approval_state",    "string",  False, enum=["DRAFT","APPROVED","LIVE","RETIRED"]),
            _f("budget_cap",        "decimal", True,  desc="Max trade or markdown budget exposure."),
        ],
    },
    "MERML.Transaction": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Silver",
        "description": "Sales transaction line — one row per item per receipt. Grain on which margin, mix, and elasticity models are built.",
        "primary_key": ["transaction_id", "line_no"],
        "fields": [
            _f("transaction_id", "string",   False, key=True, desc="Receipt / order identifier."),
            _f("line_no",        "integer",  False, key=True, desc="Line number within the transaction."),
            _f("store_id",       "string",   False, desc="FK → OPSML.Site."),
            _f("item_id",        "string",   False, desc="FK → MERML.Item."),
            _f("quantity",       "decimal",  False, desc="Units sold (negative for returns)."),
            _f("gross_amount",   "decimal",  False, desc="Pre-discount line amount."),
            _f("net_amount",     "decimal",  False, desc="Post-discount line amount."),
            _f("tax_amount",     "decimal",  False, desc="Tax applied to the line."),
            _f("promotion_id",   "string",   True,  desc="FK → MERML.Promotion if applied."),
            _f("loyalty_id",     "string",   True,  classification="member_only", desc="FK → CXML.LoyaltyMember if attached."),
            _f("transaction_ts", "timestamp",False, desc="Time of sale."),
            _f("payment_method_token","string",True, classification="pci", desc="Tokenized payment method."),
        ],
    },
    "MERML.Assortment": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Silver",
        "description": "Assortment plan — the curated list of items by store cluster and season. Derived from concept, range, and cluster decisions; published to OPSML for execution.",
        "primary_key": ["assortment_id"],
        "fields": [
            _f("assortment_id",   "string",  False, key=True),
            _f("season_code",     "string",  False),
            _f("cluster_id",      "string",  False, desc="Store cluster the assortment applies to."),
            _f("item_id",         "string",  False, desc="FK → MERML.Item."),
            _f("role",            "string",  False, enum=["TRAFFIC","DESTINATION","ROUTINE","SEASONAL","CONVENIENCE"], desc="Category role."),
            _f("depth",           "integer", False, desc="Planned weeks-of-cover at peak."),
            _f("planned_otb",     "decimal", False, desc="Open-to-buy allocated to this assortment line."),
            _f("approval_state",  "string",  False, enum=["DRAFT","APPROVED","LOCKED"]),
            _f("effective_from",  "date",    False),
            _f("effective_to",    "date",    True),
        ],
    },
    "MERML.Vendor": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Silver",
        "description": "Vendor master — the supplier as the merchant negotiates with. Carries lead time, payment terms, and trade agreements.",
        "primary_key": ["vendor_id"],
        "fields": [
            _f("vendor_id",          "string", False, key=True),
            _f("vendor_name",        "string", False),
            _f("gln",                "string", True,  desc="GS1 Global Location Number."),
            _f("payment_terms_days", "integer",False, desc="Net days."),
            _f("lead_time_days",     "integer",False, desc="Standard ship-to-DC lead time."),
            _f("contact_email_token","string", True,  classification="pii"),
            _f("scorecard_grade",    "string", True,  enum=["A","B","C","D","F"]),
            _f("tier_classification","string", True,  enum=["STRATEGIC","CORE","TRANSACTIONAL","TAIL"]),
            _f("active",             "boolean",False),
        ],
    },
    "MERML.Price": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Silver",
        "description": "Active price record — base price, competitive override, or zone variant. SCD2 across effective intervals.",
        "primary_key": ["item_id", "store_id", "kind", "effective_from"],
        "fields": [
            _f("item_id",        "string",   False, key=True, desc="FK → MERML.Item."),
            _f("store_id",       "string",   False, key=True),
            _f("kind",           "string",   False, key=True, enum=["BASE","PROMO","CLEARANCE","COMPETITIVE","ZONE"]),
            _f("amount",         "decimal",  False, desc="Posted shelf price."),
            _f("currency_code",  "string",   False, desc="ISO-4217."),
            _f("effective_from", "timestamp",False, key=True),
            _f("effective_to",   "timestamp",True),
            _f("approval_state", "string",   False, enum=["DRAFT","APPROVED","LIVE","WITHDRAWN"]),
            _f("competitor_ref", "string",   True,  desc="Competitor SKU or scrape id, if competitive."),
        ],
    },
    "MERML.Markdown": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Silver",
        "description": "Markdown event — a price reduction taken to clear, salvage, or respond to competition. Drives sell-through forecasts and salvage write-down accounting.",
        "primary_key": ["item_id", "store_id", "applied_at"],
        "fields": [
            _f("item_id",     "string",   False, key=True),
            _f("store_id",    "string",   False, key=True),
            _f("applied_at",  "timestamp",False, key=True),
            _f("reason",      "string",   False, enum=["SEASONAL","OVERSTOCK","DAMAGED","EXPIRATION","COMPETITIVE","CLEARANCE"]),
            _f("from_price",  "decimal",  False),
            _f("to_price",    "decimal",  False),
            _f("expected_sellthru_pct","decimal",True),
            _f("approver",    "string",   False, desc="Userid or agent id that signed off."),
            _f("approval_state","string", False, enum=["DRAFT","APPROVED","LIVE","REVERSED"]),
        ],
    },
    "MERML.Elasticity": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Gold",
        "description": "Modeled price elasticity — output of econometric or ML elasticity models that the agentic pricing service consults before proposing price changes.",
        "primary_key": ["item_id", "store_cluster_id", "model_run_id"],
        "fields": [
            _f("item_id",          "string",  False, key=True),
            _f("store_cluster_id", "string",  False, key=True),
            _f("model_run_id",     "string",  False, key=True, desc="FK → MLOps run id."),
            _f("elasticity",       "decimal", False, desc="Own-price elasticity coefficient."),
            _f("cross_elasticity_json","json",True,  desc="Cross-price effects against substitutes/complements."),
            _f("confidence",       "decimal", False, desc="0-1, model self-reported."),
            _f("estimated_at",     "timestamp",False),
            _f("valid_until",      "timestamp",True),
        ],
    },
    "MERML.Planogram": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Silver",
        "description": "Shelf layout — the planogram for a store/section combining facings, holding capacity, and replenishment min/max. Drives OSA monitoring.",
        "primary_key": ["planogram_id"],
        "fields": [
            _f("planogram_id",   "string", False, key=True),
            _f("store_id",       "string", False),
            _f("section_id",     "string", False, desc="Aisle/bay/section identifier."),
            _f("item_id",        "string", False, desc="FK → MERML.Item."),
            _f("facings",        "integer",False, desc="Number of facings allocated."),
            _f("capacity",       "integer",False, desc="Holding capacity in eaches."),
            _f("min_on_shelf",   "integer",False, desc="Replenishment trigger."),
            _f("max_on_shelf",   "integer",False),
            _f("effective_from", "date",   False),
            _f("effective_to",   "date",   True),
        ],
    },
    "MERML.Recipe": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Silver",
        "description": "Recipe / bill-of-materials — for prepared foods, foodservice, and CPG manufactured items. Composes with MFGML.Run and OPSML.KitchenRun.",
        "primary_key": ["recipe_id"],
        "fields": [
            _f("recipe_id",   "string", False, key=True),
            _f("recipe_name", "string", False),
            _f("yield_qty",   "decimal",False, desc="Number of servings/units produced."),
            _f("yield_uom",   "string", False),
            _f("ingredients_json","json",False, desc="Ordered ingredient list with quantities and substitution rules."),
            _f("allergens",   "array<string>", True, desc="USDA / FDA allergen labels."),
            _f("version",     "string", False, desc="SemVer of the recipe spec."),
            _f("approved_by", "string", True),
        ],
    },
    "MERML.Deduction": {
        "namespace": "MERML", "domain": "Merchandising", "layer": "Silver",
        "description": "Trade deduction — short-pay or chargeback against a vendor invoice. The leakage source that Trade Promotion & RGM service is built to recover.",
        "primary_key": ["deduction_id"],
        "fields": [
            _f("deduction_id",   "string",  False, key=True),
            _f("vendor_id",      "string",  False, desc="FK → MERML.Vendor."),
            _f("invoice_ref",    "string",  False),
            _f("deduction_type", "string",  False, enum=["TRADE","SLOTTING","COMPLIANCE","SHORTAGE","RETURN","UNAUTHORIZED"]),
            _f("amount",         "decimal", False),
            _f("currency_code",  "string",  False),
            _f("status",         "string",  False, enum=["OPEN","DISPUTED","RECOVERED","WRITTEN_OFF"]),
            _f("opened_at",      "timestamp", False),
            _f("closed_at",      "timestamp", True),
        ],
    },

    # ============================================================
    # CXML — Customer Experience (10 entities)
    # ============================================================
    "CXML.Audience": {
        "namespace": "CXML", "domain": "Customer Experience", "layer": "Silver",
        "description": "Targeting audience — a segment definition that drives campaigns, offers, and personalization. Snapshotted membership lives in SEGMENT_MEMBERSHIP equivalents.",
        "primary_key": ["audience_id"],
        "fields": [
            _f("audience_id",      "string", False, key=True),
            _f("audience_name",    "string", False),
            _f("definition_json",  "json",   False, desc="Logical predicate (rules, ML score, lookalike seed)."),
            _f("size_estimate",    "integer",False, desc="Counted membership at last refresh."),
            _f("refresh_cadence",  "string", False, enum=["REALTIME","HOURLY","DAILY","WEEKLY","ADHOC"]),
            _f("owner",            "string", False),
            _f("status",           "string", False, enum=["DRAFT","ACTIVE","ARCHIVED"]),
            _f("last_refreshed_at","timestamp",True),
        ],
    },
    "CXML.Customer": {
        "namespace": "CXML", "domain": "Customer Experience", "layer": "Silver",
        "description": "Customer master — the resolved customer identity across channels. PII-classified; tokenized at-rest.",
        "primary_key": ["customer_id"],
        "fields": [
            _f("customer_id",       "string", False, key=True),
            _f("email_token",       "string", True,  classification="pii"),
            _f("phone_token",       "string", True,  classification="pii"),
            _f("first_name_token",  "string", True,  classification="pii"),
            _f("last_name_token",   "string", True,  classification="pii"),
            _f("postal_code",       "string", True),
            _f("country_code",      "string", True),
            _f("consent_marketing", "boolean",False, desc="GDPR/CPRA marketing consent flag."),
            _f("consent_analytics", "boolean",False),
            _f("created_at",        "timestamp", False),
            _f("last_active_at",    "timestamp", True),
        ],
    },
    "CXML.Session": {
        "namespace": "CXML", "domain": "Customer Experience", "layer": "Silver",
        "description": "Customer session — a contiguous web/app/store visit. Anchored by session_id; carries device, channel, and journey-stage metadata.",
        "primary_key": ["session_id"],
        "fields": [
            _f("session_id",   "string", False, key=True),
            _f("customer_id",  "string", True,  desc="FK → CXML.Customer (null for anonymous)."),
            _f("channel",      "string", False, enum=["WEB","MOBILE_WEB","APP","STORE_KIOSK","CALL_CENTER"]),
            _f("device_type",  "string", True,  enum=["DESKTOP","TABLET","PHONE","KIOSK","OTHER"]),
            _f("started_at",   "timestamp", False),
            _f("ended_at",     "timestamp", True),
            _f("entry_path",   "string", True),
            _f("exit_path",    "string", True),
            _f("ab_test_arm",  "string", True),
        ],
    },
    "CXML.Cart": {
        "namespace": "CXML", "domain": "Customer Experience", "layer": "Silver",
        "description": "Shopping cart state — the cart at a point in time, including line items, totals, and abandonment flags.",
        "primary_key": ["cart_id"],
        "fields": [
            _f("cart_id",      "string",  False, key=True),
            _f("session_id",   "string",  False, desc="FK → CXML.Session."),
            _f("customer_id",  "string",  True,  desc="FK → CXML.Customer."),
            _f("line_items_json","json",  False, desc="Array of {item_id, qty, unit_price}."),
            _f("subtotal",     "decimal", False),
            _f("discount_total","decimal",False),
            _f("status",       "string",  False, enum=["ACTIVE","ABANDONED","CONVERTED","EXPIRED"]),
            _f("updated_at",   "timestamp", False),
        ],
    },
    "CXML.Campaign": {
        "namespace": "CXML", "domain": "Customer Experience", "layer": "Silver",
        "description": "Marketing campaign definition — the unit a marketer measures spend, reach, and attribution against.",
        "primary_key": ["campaign_id"],
        "fields": [
            _f("campaign_id",   "string", False, key=True),
            _f("campaign_name", "string", False),
            _f("channel",       "string", False, enum=["EMAIL","SMS","PUSH","DISPLAY","SEARCH","SOCIAL","DIRECT_MAIL","TV","RADIO"]),
            _f("audience_id",   "string", False, desc="FK → CXML.Audience."),
            _f("budget_amount", "decimal",False),
            _f("currency_code", "string", False),
            _f("starts_at",     "timestamp", False),
            _f("ends_at",       "timestamp", False),
            _f("status",        "string", False, enum=["DRAFT","SCHEDULED","RUNNING","PAUSED","COMPLETED"]),
        ],
    },
    "CXML.Touchpoint": {
        "namespace": "CXML", "domain": "Customer Experience", "layer": "Silver",
        "description": "Marketing touchpoint — one delivered impression or engagement. Feeds attribution models and journey stitching.",
        "primary_key": ["touchpoint_id"],
        "fields": [
            _f("touchpoint_id", "string",   False, key=True),
            _f("customer_id",   "string",   True),
            _f("session_id",    "string",   True),
            _f("campaign_id",   "string",   True),
            _f("channel",       "string",   False, enum=["EMAIL","SMS","PUSH","DISPLAY","SEARCH","SOCIAL","STORE","CALL"]),
            _f("event_type",    "string",   False, enum=["IMPRESSION","CLICK","OPEN","CONVERSION","REPLY"]),
            _f("event_ts",      "timestamp",False),
            _f("attribution_weight","decimal",True, desc="MTA-assigned credit (0-1)."),
        ],
    },
    "CXML.LoyaltyMember": {
        "namespace": "CXML", "domain": "Customer Experience", "layer": "Silver",
        "description": "Loyalty enrollment — the membership record linking a customer to a loyalty program. Holds member-only and consent metadata.",
        "primary_key": ["loyalty_id"],
        "fields": [
            _f("loyalty_id",          "string",  False, key=True),
            _f("customer_id",         "string",  False, desc="FK → CXML.Customer."),
            _f("program_code",        "string",  False),
            _f("member_number_token", "string",  False, classification="member_only"),
            _f("tier_id",             "string",  False, desc="FK → CXML.Tier."),
            _f("points_balance",      "integer", False),
            _f("enrolled_at",         "timestamp", False),
            _f("status",              "string",  False, enum=["ACTIVE","SUSPENDED","CHURNED"]),
        ],
    },
    "CXML.Offer": {
        "namespace": "CXML", "domain": "Customer Experience", "layer": "Silver",
        "description": "Personalized offer — a 1:1 derivation from a Promotion targeted to a specific customer or audience. The unit of personalization economics.",
        "primary_key": ["offer_id"],
        "fields": [
            _f("offer_id",      "string",  False, key=True),
            _f("customer_id",   "string",  True),
            _f("audience_id",   "string",  True),
            _f("promotion_id",  "string",  False, desc="FK → MERML.Promotion."),
            _f("delivery_channel","string",False, enum=["EMAIL","SMS","PUSH","WEB","APP","RECEIPT"]),
            _f("expires_at",    "timestamp", True),
            _f("redeemed_at",   "timestamp", True),
            _f("redemption_value","decimal",True),
            _f("status",        "string",  False, enum=["ISSUED","DELIVERED","REDEEMED","EXPIRED","REVOKED"]),
        ],
    },
    "CXML.Tier": {
        "namespace": "CXML", "domain": "Customer Experience", "layer": "Silver",
        "description": "Loyalty tier definition — the rules for earning, redemption, and benefits at a given tier (e.g., Gold, Platinum).",
        "primary_key": ["tier_id"],
        "fields": [
            _f("tier_id",       "string", False, key=True),
            _f("program_code",  "string", False),
            _f("tier_name",     "string", False),
            _f("threshold_spend","decimal",True, desc="Annual spend qualifier."),
            _f("earn_multiplier","decimal",False, desc="Points earned per dollar."),
            _f("benefits_json", "json",   True,  desc="Free shipping, perks, multiplier events."),
            _f("active",        "boolean",False),
        ],
    },
    "CXML.Order": {
        "namespace": "CXML", "domain": "Customer Experience", "layer": "Silver",
        "description": "Customer order — the OMS-side record of a digital or omnichannel order. Distinct from MERML.Transaction (POS-side line) — composes via order_id ↔ transaction_id mapping.",
        "primary_key": ["order_id"],
        "fields": [
            _f("order_id",       "string",   False, key=True),
            _f("customer_id",    "string",   True,  desc="FK → CXML.Customer."),
            _f("channel",        "string",   False, enum=["WEB","APP","STORE","MARKETPLACE","CALL_CENTER"]),
            _f("fulfillment_method","string",False, enum=["SHIP","BOPIS","BORIS","CURBSIDE","SAME_DAY","SHIP_FROM_STORE"]),
            _f("subtotal",       "decimal",  False),
            _f("tax_total",      "decimal",  False),
            _f("shipping_total", "decimal",  False),
            _f("grand_total",    "decimal",  False),
            _f("currency_code",  "string",   False),
            _f("payment_method_token","string",True, classification="pci"),
            _f("placed_at",      "timestamp",False),
            _f("status",         "string",   False, enum=["PLACED","PICKED","SHIPPED","DELIVERED","CANCELLED","RETURNED"]),
        ],
    },

    # ============================================================
    # SCML — Supply Chain (4 entities)
    # ============================================================
    "SCML.Inventory": {
        "namespace": "SCML", "domain": "Supply Chain", "layer": "Silver",
        "description": "Inventory position — store, DC, or dark-store on-hand at a point in time. The grain on which replenishment, allocation, and fulfillment decisions are made.",
        "primary_key": ["location_id", "item_id", "event_ts"],
        "fields": [
            _f("location_id",     "string",   False, key=True),
            _f("item_id",         "string",   False, key=True, desc="FK → MERML.Item."),
            _f("event_ts",        "timestamp",False, key=True),
            _f("on_hand",         "decimal",  False, desc="Physical units on-hand."),
            _f("on_order",        "decimal",  False, desc="Units on inbound POs."),
            _f("allocated",       "decimal",  False, desc="Units allocated to outbound (orders, transfers)."),
            _f("available",       "decimal",  False, desc="On_hand - allocated."),
            _f("days_of_supply",  "decimal",  True),
            _f("safety_stock",    "decimal",  True),
        ],
    },
    "SCML.Lot": {
        "namespace": "SCML", "domain": "Supply Chain", "layer": "Silver",
        "description": "Lot / batch — the unit of cold-chain trace, recall, and provenance. Anchored by lot_number; chains through every receiving and shipment event.",
        "primary_key": ["lot_id"],
        "fields": [
            _f("lot_id",       "string",   False, key=True),
            _f("lot_number",   "string",   False, desc="Vendor or producer lot identifier."),
            _f("item_id",      "string",   False, desc="FK → MERML.Item."),
            _f("vendor_id",    "string",   False),
            _f("produced_at",  "timestamp",True),
            _f("expires_at",   "timestamp",True),
            _f("country_of_origin","string",True, desc="ISO-3166 alpha-2."),
            _f("status",       "string",   False, enum=["ACTIVE","HOLD","RECALLED","CONSUMED"]),
        ],
    },
    "SCML.Shipment": {
        "namespace": "SCML", "domain": "Supply Chain", "layer": "Silver",
        "description": "Advanced shipment notice (ASN) and inbound shipment record — the carrier-level unit of supply-chain visibility.",
        "primary_key": ["shipment_id"],
        "fields": [
            _f("shipment_id",  "string",   False, key=True),
            _f("sscc",         "string",   True,  desc="GS1 Serial Shipping Container Code."),
            _f("vendor_id",    "string",   False),
            _f("origin_gln",   "string",   True),
            _f("destination_id","string",  False, desc="DC or store location id."),
            _f("carrier_code", "string",   True),
            _f("departed_at",  "timestamp",True),
            _f("eta",          "timestamp",True),
            _f("arrived_at",   "timestamp",True),
            _f("status",       "string",   False, enum=["PLANNED","IN_TRANSIT","DELIVERED","DELAYED","LOST"]),
        ],
    },
    "SCML.Return": {
        "namespace": "SCML", "domain": "Supply Chain", "layer": "Silver",
        "description": "Customer return event — the trigger for refund processing, fraud screening, and reverse logistics routing.",
        "primary_key": ["return_id"],
        "fields": [
            _f("return_id",   "string",   False, key=True),
            _f("order_id",    "string",   True,  desc="FK → CXML.Order."),
            _f("customer_id", "string",   True),
            _f("item_id",     "string",   False),
            _f("quantity",    "decimal",  False),
            _f("reason_code", "string",   False, enum=["DAMAGED","WRONG_ITEM","DID_NOT_FIT","CHANGED_MIND","DEFECTIVE","FRAUD_SUSPECTED"]),
            _f("refund_amount","decimal", False),
            _f("disposition", "string",   False, enum=["RESTOCK","REFURBISH","SALVAGE","DESTROY","RETURN_TO_VENDOR"]),
            _f("returned_at", "timestamp",False),
        ],
    },

    # ============================================================
    # OPSML — Operations (7 entities)
    # ============================================================
    "OPSML.Site": {
        "namespace": "OPSML", "domain": "Operations", "layer": "Silver",
        "description": "Site master — store, DC, plant, restaurant, dark store. The physical location anchor for inventory, labor, and execution telemetry.",
        "primary_key": ["site_id"],
        "fields": [
            _f("site_id",      "string", False, key=True),
            _f("site_name",    "string", False),
            _f("site_type",    "string", False, enum=["STORE","DC","DARK_STORE","PLANT","RESTAURANT","DEPOT"]),
            _f("format_id",    "string", True,  desc="FK → OPSML.Format."),
            _f("region",       "string", False),
            _f("country_code", "string", False),
            _f("postal_code",  "string", True),
            _f("opened_at",    "date",   False),
            _f("closed_at",    "date",   True),
            _f("active",       "boolean",False),
        ],
    },
    "OPSML.Format": {
        "namespace": "OPSML", "domain": "Operations", "layer": "Silver",
        "description": "Store format definition — the operating model template (e.g., 'Express', 'Supercenter', 'Drive-thru-only'). Drives assortment, labor, and capex assumptions.",
        "primary_key": ["format_id"],
        "fields": [
            _f("format_id",    "string",  False, key=True),
            _f("format_name",  "string",  False),
            _f("avg_sqft",     "decimal", True),
            _f("typical_skus", "integer", True),
            _f("operating_hours_json","json",True),
            _f("staffing_baseline","integer", True, desc="Baseline FTE per shift."),
        ],
    },
    "OPSML.Worker": {
        "namespace": "OPSML", "domain": "Operations", "layer": "Silver",
        "description": "Worker / associate master — the person who works a shift. Tightly governed by HR/wage-and-hour controls.",
        "primary_key": ["worker_id"],
        "fields": [
            _f("worker_id",      "string",  False, key=True),
            _f("worker_name_token","string",False, classification="pii"),
            _f("home_site_id",   "string",  False),
            _f("role_code",      "string",  False, enum=["CASHIER","STOCKER","DEPT_LEAD","STORE_MGR","COOK","DRIVER","PHARMACIST","OPTICIAN"]),
            _f("hire_date",      "date",    False),
            _f("term_date",      "date",    True),
            _f("min_wage_rate",  "decimal", True),
            _f("availability_json","json",  True,  desc="Weekly availability template."),
            _f("status",         "string",  False, enum=["ACTIVE","LOA","TERMINATED"]),
        ],
    },
    "OPSML.Schedule": {
        "namespace": "OPSML", "domain": "Operations", "layer": "Silver",
        "description": "Published labor schedule — the assignment of workers to shifts at a site for a week. Respects forecast, availability, and wage/hour rules.",
        "primary_key": ["schedule_id"],
        "fields": [
            _f("schedule_id",  "string",   False, key=True),
            _f("site_id",      "string",   False),
            _f("week_starting","date",     False),
            _f("worker_id",    "string",   False),
            _f("shift_start",  "timestamp",False),
            _f("shift_end",    "timestamp",False),
            _f("role_code",    "string",   False),
            _f("scheduled_hours","decimal",False),
            _f("approval_state","string",  False, enum=["DRAFT","APPROVED","PUBLISHED","LOCKED"]),
        ],
    },
    "OPSML.LaborForecast": {
        "namespace": "OPSML", "domain": "Operations", "layer": "Gold",
        "description": "Demand-driven labor forecast — minute- or 15-minute-grain demand prediction used to generate the schedule.",
        "primary_key": ["site_id", "interval_start"],
        "fields": [
            _f("site_id",         "string",   False, key=True),
            _f("interval_start",  "timestamp",False, key=True),
            _f("interval_minutes","integer",  False, desc="15, 30, or 60."),
            _f("forecast_demand", "decimal",  False, desc="Predicted units of work (transactions, orders, prep batches)."),
            _f("required_fte",    "decimal",  False),
            _f("model_run_id",    "string",   False),
            _f("forecasted_at",   "timestamp",False),
        ],
    },
    "OPSML.Task": {
        "namespace": "OPSML", "domain": "Operations", "layer": "Silver",
        "description": "Store task — a unit of orchestrated work assigned to an associate (price change, planogram reset, OSA recovery, recall pull).",
        "primary_key": ["task_id"],
        "fields": [
            _f("task_id",     "string",   False, key=True),
            _f("site_id",     "string",   False),
            _f("task_type",   "string",   False, enum=["PRICE_CHANGE","PLANOGRAM_RESET","OSA_RECOVERY","RECALL","FACINGS","CYCLE_COUNT","CLEANING","SAFETY"]),
            _f("priority",    "string",   False, enum=["P1","P2","P3","P4"]),
            _f("assigned_to", "string",   True,  desc="FK → OPSML.Worker."),
            _f("created_at",  "timestamp",False),
            _f("due_at",      "timestamp",True),
            _f("completed_at","timestamp",True),
            _f("status",      "string",   False, enum=["OPEN","ASSIGNED","IN_PROGRESS","COMPLETED","CANCELLED"]),
        ],
    },
    "OPSML.KitchenRun": {
        "namespace": "OPSML", "domain": "Operations", "layer": "Silver",
        "description": "Kitchen production run — a foodservice batch (a tray of biscuits, a fryer drop, a pizza pre-make). Composes with MERML.Recipe and MFGML.Quality.",
        "primary_key": ["run_id"],
        "fields": [
            _f("run_id",      "string",   False, key=True),
            _f("site_id",     "string",   False),
            _f("recipe_id",   "string",   False, desc="FK → MERML.Recipe."),
            _f("started_at",  "timestamp",False),
            _f("completed_at","timestamp",True),
            _f("yield_qty",   "decimal",  True),
            _f("waste_qty",   "decimal",  True),
            _f("hold_until",  "timestamp",True, desc="Food-safety hold time."),
            _f("operator_id", "string",   True),
        ],
    },

    # ============================================================
    # MFGML — Manufacturing (3 entities)
    # ============================================================
    "MFGML.Asset": {
        "namespace": "MFGML", "domain": "Manufacturing", "layer": "Silver",
        "description": "Plant asset master — line, station, packer, freezer, refrigeration unit. Anchored to the plant site and tied to OEE telemetry.",
        "primary_key": ["asset_id"],
        "fields": [
            _f("asset_id",   "string", False, key=True),
            _f("asset_name", "string", False),
            _f("plant_id",   "string", False, desc="FK → OPSML.Site (plant)."),
            _f("asset_type", "string", False, enum=["LINE","STATION","FILLER","CAPPER","PACKER","FREEZER","CHILLER","CONVEYOR"]),
            _f("commissioned_at","date",True),
            _f("status",     "string", False, enum=["RUNNING","IDLE","DOWN","MAINTENANCE","RETIRED"]),
        ],
    },
    "MFGML.Run": {
        "namespace": "MFGML", "domain": "Manufacturing", "layer": "Silver",
        "description": "Production run — a contiguous batch on a line. The grain on which OEE, yield, and quality metrics roll up.",
        "primary_key": ["run_id"],
        "fields": [
            _f("run_id",       "string",   False, key=True),
            _f("asset_id",     "string",   False, desc="FK → MFGML.Asset."),
            _f("recipe_id",    "string",   True,  desc="FK → MERML.Recipe (CPG)."),
            _f("started_at",   "timestamp",False),
            _f("ended_at",     "timestamp",True),
            _f("planned_qty",  "decimal",  False),
            _f("actual_qty",   "decimal",  True),
            _f("yield_pct",    "decimal",  True),
            _f("downtime_minutes","decimal",True),
            _f("oee_score",    "decimal",  True, desc="0-1, calculated availability * performance * quality."),
        ],
    },
    "MFGML.Quality": {
        "namespace": "MFGML", "domain": "Manufacturing", "layer": "Silver",
        "description": "Quality check / inspection — a sampled or in-line measurement against spec. Triggers HOLD, REWORK, or DESTROY dispositions.",
        "primary_key": ["check_id"],
        "fields": [
            _f("check_id",    "string",   False, key=True),
            _f("run_id",      "string",   False, desc="FK → MFGML.Run."),
            _f("spec_code",   "string",   False),
            _f("measurement", "decimal",  False),
            _f("uom",         "string",   False),
            _f("within_spec", "boolean",  False),
            _f("disposition", "string",   False, enum=["RELEASE","HOLD","REWORK","DESTROY"]),
            _f("inspector_id","string",   True),
            _f("checked_at",  "timestamp",False),
        ],
    },

    # ============================================================
    # FINML — Finance (5 entities)
    # ============================================================
    "FINML.GL": {
        "namespace": "FINML", "domain": "Finance", "layer": "Silver",
        "description": "General ledger entry — the canonical financial journal row. The endpoint of every revenue, cost, and accrual chain.",
        "primary_key": ["gl_entry_id"],
        "fields": [
            _f("gl_entry_id",  "string",   False, key=True),
            _f("posting_date", "date",     False),
            _f("account_code", "string",   False),
            _f("cost_center",  "string",   True),
            _f("debit_amount", "decimal",  False),
            _f("credit_amount","decimal",  False),
            _f("currency_code","string",   False),
            _f("source_doc",   "string",   True,  desc="Originating doc id (invoice, transaction, run)."),
            _f("posted_by",    "string",   False),
            _f("posted_at",    "timestamp",False),
        ],
    },
    "FINML.Lease": {
        "namespace": "FINML", "domain": "Finance", "layer": "Silver",
        "description": "Real estate lease — the multi-year obligation against a site. Source of CAM reconciliation, ASC-842 accounting, and renewal/termination decisions.",
        "primary_key": ["lease_id"],
        "fields": [
            _f("lease_id",     "string",  False, key=True),
            _f("site_id",      "string",  False),
            _f("landlord_name","string",  False),
            _f("starts_at",    "date",    False),
            _f("ends_at",      "date",    False),
            _f("base_rent_monthly","decimal",False),
            _f("currency_code","string",  False),
            _f("escalation_pct","decimal",True),
            _f("cam_clause",   "string",  True),
            _f("renewal_options_json","json",True),
            _f("status",       "string",  False, enum=["ACTIVE","NEGOTIATING","EXPIRING","TERMINATED"]),
        ],
    },
    "FINML.Settlement": {
        "namespace": "FINML", "domain": "Finance", "layer": "Silver",
        "description": "Payment settlement — the bank/processor side of a transaction. Reconciliation feed against POS/OMS revenue.",
        "primary_key": ["settlement_id"],
        "fields": [
            _f("settlement_id","string",  False, key=True),
            _f("processor",    "string",  False),
            _f("batch_id",     "string",  False),
            _f("gross_amount", "decimal", False),
            _f("fee_amount",   "decimal", False),
            _f("net_amount",   "decimal", False),
            _f("currency_code","string",  False),
            _f("settled_at",   "timestamp",False),
            _f("reconciled",   "boolean", False),
            _f("variance_amount","decimal",True),
        ],
    },
    "FINML.Tax": {
        "namespace": "FINML", "domain": "Finance", "layer": "Silver",
        "description": "Tax accrual / filing — the unit on which the indirect-tax engine settles. Composes with GL for posting and Settlement for refund/remit.",
        "primary_key": ["tax_record_id"],
        "fields": [
            _f("tax_record_id","string",  False, key=True),
            _f("jurisdiction", "string",  False),
            _f("tax_type",     "string",  False, enum=["SALES","VAT","GST","EXCISE","DUTY","WITHHOLDING"]),
            _f("period_start", "date",    False),
            _f("period_end",   "date",    False),
            _f("taxable_base", "decimal", False),
            _f("tax_rate",     "decimal", False),
            _f("tax_due",      "decimal", False),
            _f("filed_at",     "timestamp",True),
            _f("status",       "string",  False, enum=["ACCRUING","FILED","PAID","DISPUTED"]),
        ],
    },
    "FINML.TradeSpend": {
        "namespace": "FINML", "domain": "Finance", "layer": "Silver",
        "description": "Trade promotion spend record — manufacturer trade dollars committed to a retailer event. Source of trade-spend ROI and deduction reconciliation.",
        "primary_key": ["trade_spend_id"],
        "fields": [
            _f("trade_spend_id","string", False, key=True),
            _f("vendor_id",    "string",  False),
            _f("retailer_id",  "string",  False),
            _f("promotion_id", "string",  True,  desc="FK → MERML.Promotion."),
            _f("committed_amount","decimal",False),
            _f("paid_amount",  "decimal", True),
            _f("currency_code","string",  False),
            _f("approved_at",  "timestamp",True),
            _f("status",       "string",  False, enum=["COMMITTED","INVOICED","PAID","DISPUTED","REVERSED"]),
        ],
    },

    # ============================================================
    # RISKML — Risk & Compliance (1 entity)
    # ============================================================
    "RISKML.Event": {
        "namespace": "RISKML", "domain": "Risk & Compliance", "layer": "Silver",
        "description": "Risk event — a fraud, ATO, ORC, shrink, cyber, safety, or compliance signal. The single feed the trust-perimeter agents triage.",
        "primary_key": ["event_id"],
        "fields": [
            _f("event_id",   "string",   False, key=True),
            _f("event_type", "string",   False, enum=["FRAUD","ATO","ORC","SHRINK","CYBER","SAFETY","COMPLIANCE","INSIDER"]),
            _f("severity",   "string",   False, enum=["LOW","MEDIUM","HIGH","CRITICAL"]),
            _f("subject_type","string",  False, enum=["TRANSACTION","ACCOUNT","SHIPMENT","WORKER","SITE","SYSTEM"]),
            _f("subject_id", "string",   False),
            _f("detected_at","timestamp",False),
            _f("confidence", "decimal",  True, desc="0-1 model score."),
            _f("disposition","string",   False, enum=["OPEN","INVESTIGATING","CONFIRMED","FALSE_POSITIVE","CLOSED"]),
            _f("loss_amount","decimal",  True),
        ],
    },

    # ============================================================
    # ESGML — Sustainability & ESG (1 entity)
    # ============================================================
    "ESGML.Emission": {
        "namespace": "ESGML", "domain": "Sustainability & ESG", "layer": "Silver",
        "description": "Carbon emission record — a measured or modeled emission attributed to a site, run, shipment, or supplier. Feeds Scope-1/2/3 disclosures.",
        "primary_key": ["emission_id"],
        "fields": [
            _f("emission_id", "string",   False, key=True),
            _f("scope",       "string",   False, enum=["SCOPE_1","SCOPE_2_LOCATION","SCOPE_2_MARKET","SCOPE_3"]),
            _f("category",    "string",   False, desc="GHG Protocol category (e.g., Cat 1 Purchased Goods)."),
            _f("source_type", "string",   False, enum=["SITE","RUN","SHIPMENT","SUPPLIER","PRODUCT"]),
            _f("source_id",   "string",   False),
            _f("co2e_kg",     "decimal",  False, desc="Kilograms of CO2 equivalent."),
            _f("calc_method", "string",   False, enum=["METERED","SUPPLIER_SPECIFIC","AVERAGE_DATA","SPEND_BASED"]),
            _f("period_start","date",     False),
            _f("period_end",  "date",     False),
            _f("verified",    "boolean",  False, desc="Third-party verified."),
        ],
    },
}
